#pragma once

#include "stdafx.h"

class DirectInput8A : public IDirectInput8A {
	STDMETHOD(QueryInterface)(REFIID riid, LPVOID *ppvObj);
	STDMETHOD_(ULONG, AddRef)(void);
	STDMETHOD_(ULONG, Release)(void);
	STDMETHOD(CreateDevice)(REFGUID, LPDIRECTINPUTDEVICE8A *, LPUNKNOWN);
	STDMETHOD(EnumDevices)(DWORD, LPDIENUMDEVICESCALLBACKA, LPVOID, DWORD);
	STDMETHOD(GetDeviceStatus)(REFGUID);
	STDMETHOD(RunControlPanel)(HWND, DWORD);
	STDMETHOD(Initialize)(HINSTANCE, DWORD);
	STDMETHOD(FindDevice)(REFGUID, LPCSTR, LPGUID);
	STDMETHOD(EnumDevicesBySemantics)(LPCSTR, LPDIACTIONFORMATA, LPDIENUMDEVICESBYSEMANTICSCBA, LPVOID, DWORD);
	STDMETHOD(ConfigureDevices)(LPDICONFIGUREDEVICESCALLBACK, LPDICONFIGUREDEVICESPARAMSA, DWORD, LPVOID);
};
